#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
if (!defined('APPLICATION_ENV')) {
	if (getenv('APPLICATION_ENV') != false) {
		define('APPLICATION_ENV', getenv('APPLICATION_ENV'));
	} else {
		define('APPLICATION_ENV', 'prod');
	}
}

$env = require(__DIR__.'/config/env.php');

defined('YII_DEBUG') or define('YII_DEBUG', $env['debug']);
defined('YII_ENV') or define('YII_ENV', APPLICATION_ENV);

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
